apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: ghcr.io/issamhot69/ai-banking-platform/account-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: bank-config
            - secretRef:
                name: bank-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: bank
spec:
  selector:
    app: account-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
